#+title: ultra-scroll - Changelog
#+author: J.D. Smith
#+language: en

* Development

- Change to custom group ~scrolling~.
- Improve ultra-scroll-check to correctly interrogate a group of wheel events to determine if they are "real" or fake.  Some Linux systems report ~PIXEL-DELTA~'s with fixed values (a line height), which effectively reverts ~ultra-scroll~ to line-by-line scrolling.
- Check for ~--with-xinput2~ on Linux and warning if not found (needed for pixel scrolling; see #14).

* v0.2.1 (2025-01-09)

- Introduce ~ultra-scroll-check~, to provide a means for users to check their wheel event stream for real pixel delta scroll data.    

* v0.2 (2025-01-08)

- Support all (compatible) builds and hardware using the ~PIXEL-DELTA~ data in wheel events, continuing to support ~emacs-mac~ style wheel events too.
- Rename to ~ultra-scroll~.
- Update documentation.

* v0.1 (2024-04-06)

- Reduce garbage collection during scroll with new configuration options.
- Many documentation improvements.

* v0.0.1 (2023-11-28)

- Introduced, supporting ~emacs-mac~ wheel events.
