#+title: ultra-scroll - Changelog
#+author: J.D. Smith
#+language: en

* v0.3.3 (2025-03-11)

- Do not move point to ~point-min/max~ when scroll reaches buffer beginning/end, unless the cursor has been hidden.

* v0.3.2 (2025-01-26)

- Re-enable ~make-cursor-line-fully-visible~, which recent versions of ~pixel-scroll-precision-mode~ disable.

* v0.3.1 (2025-01-18)

- Add ~ultra-scroll-hide-functions~ hook, to support disabling/re-enabling arbitrary modes or calling other functions when scrolling starts/stops.
- Doc improvements.

* v0.3 (2025-01-12)

- Hide cursor (and ~hl-line~) during scrolls by default.  See ~ultra-scroll-hide-cursor~.  Thanks to @minad; see #15.
- Put custom variables in group ~scrolling~.
- Improve ~ultra-scroll-check~:
  + Correctly interrogate a group of wheel events to determine if they are "real" or fake.  Some Linux systems report ~PIXEL-DELTA~'s with fixed values (a line height), which effectively reverts ~ultra-scroll~ to line-by-line scrolling.
  + Guard against up+down scrolling falsely indicating diverse scrolls pixel offsets.
  + Report event timing (how fast /is/ your mouse)?
- Check for ~--with-xinput2~ on Linux and warning if not found (needed for pixel scrolling; see #14).
- Enable ~pixel-scroll-precision-mode~ directly, rather than just re-using its keymap.  This allows commands like ~vertico-mouse~ to turn off ~ultra-scroll~ indirectly by disabling ~pixel-scroll-precision-mode~.  

* v0.2.1 (2025-01-09)

- Introduce ~ultra-scroll-check~, to provide a means for users to check their wheel event stream for real pixel delta scroll data.    

* v0.2 (2025-01-08)

- Support all (compatible) builds and hardware using the ~PIXEL-DELTA~ data in wheel events, continuing to support ~emacs-mac~ style wheel events too.
- Rename to ~ultra-scroll~.
- Update documentation.

* v0.1 (2024-04-06)

- Reduce garbage collection during scroll with new configuration options.
- Many documentation improvements.

* v0.0.1 (2023-11-28)

- Introduced, supporting ~emacs-mac~ wheel events.
